apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.16.212
    path: "/data/nfs/exports"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector: 
    matchLabels:
      app: mariadb
