apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
  - name: mariadb
    port: 3306
    targetPort: mariadb
  - name: mysql
    port: 3306
    targetPort: mariadb
  - name: metrics
    port: 9104
    targetPort: metrics
  selector:
    app: mariadb
