apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rstudio
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rstudio.apps.datascience.psu.edu
    http:
      paths:
      - path: /
        backend:
          serviceName: rstudio
          servicePort: 8787
